[connections.snowflake]
account = "VBEJHGR-PNB74545"
user = "MARIORIZ1"
password = "St1c@zzi123456"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
